[package]
name = "tarotv2"
version = "1.2.0"
upgrade_policy = "compatible"

[addresses]
admin = "0x973d0f394a028c4fc74e069851114509e78aba9e91f52d000df2d7e40ec5205b"
treasury = "0x973d0f394a028c4fc74e069851114509e78aba9e91f52d000df2d7e40ec5205b"

[dependencies]
AptosFramework = { local = "../../../aptos/aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "../../../aptos/aptos-core/aptos-move/framework/aptos-stdlib" }
AptosTokenObjects = { local = "../../../aptos/aptos-core/aptos-move/framework/aptos-token-objects" }